index:
    path: /
    controller: App\Controller\DefaultController::index
aboutUs:
    path: /o-nas
    controller: App\Controller\CompanyController::aboutUs
kontactGet:
    path: /kontakt
    methods: [GET]
    controller: App\Controller\ContactFormController::show

kontactPost:
    path: /kontakt
    methods: [POST]
    controller: App\Controller\ContactFormController::post

orderDetails:
    path: /zamowienie/{id}
    controller: App\Controller\PetStoreController::getOrder
    requirements:
        id: '\d+'